# FROM node:23-alpine
# # FROM node:slim

# WORKDIR /app

# # Instala dependências
# COPY package*.json ./
# RUN npm ci

# # Copia o código
# COPY . .

# # Compila o projeto (se usar TypeScript)
# RUN npm run build

# # Expõe a porta da aplicação + métricas
# EXPOSE 3000

# CMD ["npm", "run", "start:prod"]