services:
  db:
    image: postgres:16-alpine
    container_name: colibri_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - localnet

  redis:
    image: redis:7-alpine
    container_name: colibri_redis
    restart: always
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - localnet

volumes:
  postgres_data:
  redis_data:

networks:
  localnet:
    driver: bridge
