version: '3.9'

services:
  api:
    build: .
    container_name: colibri_api
    restart: always
    env_file: .env
    ports:
      - '${PORT:-3000}:3000'
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    container_name: colibri_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: colibri_redis
    restart: always
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
