-- CreateEnum
CREATE TYPE "PropertyType" AS ENUM ('APARTAMENTO', 'APARTAMENTO_DUPLEX', 'APARTAMENTO_TRIPLEX', 'CASA', 'CHACARA', 'KITNET', 'LOJA_SALA', 'PREDIO', 'TERRENO');

-- AlterTable
ALTER TABLE "Property" ADD COLUMN     "propertyType" "PropertyType" NOT NULL DEFAULT 'APARTAMENTO';
