
global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules.yml" 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'colibri-api'
    static_configs:
      - targets: ['api:3000']