global:
  scrape_interval: 15s # A cada 15 segundos, o Prometheus vai buscar as métricas

scrape_configs:
  # O primeiro "alvo" é o próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # O segundo "alvo" é o nosso exportador de métricas do Redis
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121'] # O nome do serviço no Docker Compose