entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: "https"
  https:
    address: ":443"

providers:
  docker:
    exposedByDefault: false # Mais seguro, expõe apenas containers com labels

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${LETSENCRYPT_EMAIL}
      storage: "acme.json"
      httpChallenge:
        entryPoint: "http"